language: r
r: bioc-release

addons:
  apt:
    packages:
      - r-cran-rjava

r_packages:
  - gridExtra
  - rJava

bioc_packages:
  - BiocGenerics
  - Biostrings
  - org.Hs.eg.db
  - GOSemSim
  - ChemmineR
  - fmcsR
