language: r
r: bioc-devel

addons:
  apt:
    packages:
      - r-cran-rjava

r_packages: gridExtra

bioc_packages:
  - BiocGenerics
  - Biostrings
  - org.Hs.eg.db
  - GOSemSim
  - ChemmineR
  - fmcsR
